# This file is machine-generated - editing it directly is not advised

[[VecTargets]]
deps = ["BSON", "Distributions", "DistributionsAD", "Parameters", "Random", "ReverseDiff", "StatsFuns"]
git-tree-sha1 = "7f92768bddfc8fc3a4f7ee502b1c273f4a75417e"
repo-rev = "main"
repo-url = "https://github.com/xukai92/VecTargets.jl"
uuid = "8a639fad-7908-4fe4-8003-906e9297f002"
version = "0.1.0"
