#= generated by Comonicon =#
function command_main(ARGS::Vector{String} = ARGS)
    ccall(:jl_exit_on_sigint, Cvoid, (Cint,), 0)
    var"##help#463" = if isempty(ARGS)
            1
        else
            -1
        end
    var"##version#464" = -1
    for i = 1:length(ARGS)
        x = ARGS[i]
        if x == "--help" || x == "-h"
            var"##help#463" = i
            break
        end
        if x == "--version" || x == "-V"
            var"##version#464" = i
            break
        end
    end
    if var"##help#463" >= 1
        print("\n  \e[94m\e[1mexp_gmm\e[22m\e[39m\n\n\n\n\e[0m\e[1mUsage\e[22m\n\n  \e[94m\e[1mexp_gmm\e[22m\e[39m\e[96m [options]\e[39m \e[95m<TS>\e[39m \e[95m<epsilon::Float64>\e[39m \e[95m<L::Int64>\e[39m\n\n\e[0m\e[1mArgs\e[22m\n\n  \e[95m<L::Int64>\e[39m\n\n  \e[95m<TS>\e[39m\n\n  \e[95m<epsilon::Float64>\e[39m\n\n\e[0m\e[1mOptions\e[22m\n\n  \e[96m--gamma\e[39m \e[95m<arg::Float64>\e[39m\n\n  \e[96m--n_mc\e[39m \e[95m<arg::Int64>\e[39m\n\n  \e[96m--n_samples_max\e[39m \e[95m<arg::Int64>\e[39m\n\n  \e[96m--sigma\e[39m \e[95m<arg::Float64>\e[39m\n\n\e[0m\e[1mFlags\e[22m\n\n  \e[96m-h, --help\e[39m                      print this help message\n\n  \e[96m-V, --version\e[39m                   print version information\n\n\n")
        return 0
    end
    if var"##version#464" >= 1
        println("\e[94m\e[1mexp_gmm\e[22m\e[39m")
        return 0
    end
    var"##parameters#465" = []
    var"##index#468" = 1
    while !(isempty(ARGS)) && 1 <= var"##index#468" <= length(ARGS)
        var"##arg#467" = ARGS[var"##index#468"]
        if startswith(var"##arg#467", "-")
            var"##m#469" = match(r"^--n_mc$", var"##arg#467")
            if var"##m#469" === nothing
                var"##m#470" = match(r"^--n_mc=(.*)", var"##arg#467")
                if var"##m#470" === nothing
                    var"##m#471" = match(r"^--n_samples_max$", var"##arg#467")
                    if var"##m#471" === nothing
                        var"##m#472" = match(r"^--n_samples_max=(.*)", var"##arg#467")
                        if var"##m#472" === nothing
                            var"##m#473" = match(r"^--gamma$", var"##arg#467")
                            if var"##m#473" === nothing
                                var"##m#474" = match(r"^--gamma=(.*)", var"##arg#467")
                                if var"##m#474" === nothing
                                    var"##m#475" = match(r"^--sigma$", var"##arg#467")
                                    if var"##m#475" === nothing
                                        var"##m#476" = match(r"^--sigma=(.*)", var"##arg#467")
                                        if var"##m#476" === nothing
                                            error("Error: unknown option: $(var"##arg#467"), use -h or --help to check more detailed help info")
                                        else
                                            push!(var"##parameters#465", :sigma => convert(Float64, Meta.parse(String(var"##m#476"[1]))))
                                            deleteat!(ARGS, var"##index#468")
                                            var"##index#468" = var"##index#468" - 1
                                        end
                                    else
                                        var"##index#468" < length(ARGS) || error("expect an argument")
                                        push!(var"##parameters#465", :sigma => convert(Float64, Meta.parse(ARGS[var"##index#468" + 1])))
                                        deleteat!(ARGS, (var"##index#468", var"##index#468" + 1))
                                        var"##index#468" = var"##index#468" - 1
                                    end
                                else
                                    push!(var"##parameters#465", :gamma => convert(Float64, Meta.parse(String(var"##m#474"[1]))))
                                    deleteat!(ARGS, var"##index#468")
                                    var"##index#468" = var"##index#468" - 1
                                end
                            else
                                var"##index#468" < length(ARGS) || error("expect an argument")
                                push!(var"##parameters#465", :gamma => convert(Float64, Meta.parse(ARGS[var"##index#468" + 1])))
                                deleteat!(ARGS, (var"##index#468", var"##index#468" + 1))
                                var"##index#468" = var"##index#468" - 1
                            end
                        else
                            push!(var"##parameters#465", :n_samples_max => convert(Int64, Meta.parse(String(var"##m#472"[1]))))
                            deleteat!(ARGS, var"##index#468")
                            var"##index#468" = var"##index#468" - 1
                        end
                    else
                        var"##index#468" < length(ARGS) || error("expect an argument")
                        push!(var"##parameters#465", :n_samples_max => convert(Int64, Meta.parse(ARGS[var"##index#468" + 1])))
                        deleteat!(ARGS, (var"##index#468", var"##index#468" + 1))
                        var"##index#468" = var"##index#468" - 1
                    end
                else
                    push!(var"##parameters#465", :n_mc => convert(Int64, Meta.parse(String(var"##m#470"[1]))))
                    deleteat!(ARGS, var"##index#468")
                    var"##index#468" = var"##index#468" - 1
                end
            else
                var"##index#468" < length(ARGS) || error("expect an argument")
                push!(var"##parameters#465", :n_mc => convert(Int64, Meta.parse(ARGS[var"##index#468" + 1])))
                deleteat!(ARGS, (var"##index#468", var"##index#468" + 1))
                var"##index#468" = var"##index#468" - 1
            end
        else
            var"##index#468" += 1
        end
    end
    var"##n_args#466" = length(ARGS) - 0
    if var"##n_args#466" < 3
        error("Error: command exp_gmm expect at least 3 arguments, got $(var"##n_args#466"), use -h or --help to check more detailed help info")
    end
    if var"##n_args#466" > 3
        error("Error: command exp_gmm expect at most 3 arguments, got $(var"##n_args#466"), use -h or --help to check more detailed help info")
    end
    (exp_gmm)(ARGS[1], convert(Float64, Meta.parse(ARGS[2])), convert(Int64, Meta.parse(ARGS[3])); var"##parameters#465"...)
    return 0
end
command_main()
